<?php

namespace AppBundle\Repository;

/**
 * CenyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenyRepository extends \Doctrine\ORM\EntityRepository
{
}
