<?php

namespace AppBundle\Repository;

/**
 * DatyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatyRepository extends \Doctrine\ORM\EntityRepository
{
}
