<?php

namespace AppBundle\Repository;

/**
 * TerminyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminyRepository extends \Doctrine\ORM\EntityRepository
{
}
