<?php

namespace AppBundle\Repository;

/**
 * WiadomoscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WiadomoscRepository extends \Doctrine\ORM\EntityRepository
{
}
