<?php

namespace AppBundle\Repository;

/**
 * ZapisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZapisRepository extends \Doctrine\ORM\EntityRepository
{
}
